# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kwallet': 'Frameworks/6.24'

Options:
  cmake-options: "-DINSTALL_BROKEN_SIGNON_EXTENSION=TRUE"
  require-passing-tests-on: ['Linux', 'FreeBSD']
