# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kwallet': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'

Options:
  cmake-options: "-DINSTALL_BROKEN_SIGNON_EXTENSION=TRUE"
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
